{"name": "Невозможно авторизоваться с неверными учетными данными", "status": "passed", "start": 1742965243644, "stop": 1742965244994, "uuid": "e57b132d-9e9c-435f-8f19-b5a8327c4cb9", "historyId": "1c4829e889ae76c7018b5a2212a72cea", "testCaseId": "1c4829e889ae76c7018b5a2212a72cea", "fullName": "tests.test_user.TestUser#test_cannot_login_with_wrong_credentials", "labels": [{"name": "feature", "value": "Пользователь"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUser"}, {"name": "host", "value": "LAPTOP-QVE1U26H"}, {"name": "thread", "value": "4124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user"}]}