{"name": "Невозможно авторизоваться с неверными учетными данными", "status": "passed", "start": 1742964835212, "stop": 1742964836790, "uuid": "a3f7f0f5-d3cb-4b86-a86a-b7807d4a91e0", "historyId": "1c4829e889ae76c7018b5a2212a72cea", "testCaseId": "1c4829e889ae76c7018b5a2212a72cea", "fullName": "tests.test_user.TestUser#test_cannot_login_with_wrong_credentials", "labels": [{"name": "feature", "value": "Пользователь"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUser"}, {"name": "host", "value": "LAPTOP-QVE1U26H"}, {"name": "thread", "value": "1604-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user"}]}