{"name": "Невозможно авторизоваться с неверными учетными данными", "status": "passed", "start": 1742756516574, "stop": 1742756517739, "uuid": "f33938d3-db1e-4df2-8012-9b496f475f5c", "historyId": "1c4829e889ae76c7018b5a2212a72cea", "testCaseId": "1c4829e889ae76c7018b5a2212a72cea", "fullName": "tests.test_user.TestUser#test_cannot_login_with_wrong_credentials", "labels": [{"name": "feature", "value": "Пользователь"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUser"}, {"name": "host", "value": "LAPTOP-QVE1U26H"}, {"name": "thread", "value": "3900-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user"}]}